name: Generate Pull Request

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      instance-name:
        description: 'Name of source APIM instance'
        default: 'apimdevops-dev'
        required: true
      destination-name:
        description: 'Name of destination APIM instance'
        default: 'apimdevops-qa'
        required: true
      resource-group-name:
        description: 'Name of resource group'
        default: "rg-apimdemos-devops"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Download Extractor Release
      run: |
        mkdir extractor
        cd extractor
        gh release download 1.0.0-beta.3 --repo 'Azure/azure-api-management-devops-resource-kit' --archive=zip
        ls -R
        unzip -q azure-api-management-devops-resource-kit-1.0.0-beta.3 -d ./src
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build Extractor Release
      run: |
        cd extractor
        cd src
        cd azure-api-management-devops-resource-kit-1.0.0-beta.3
        cd src 
        cd ArmTemplates
        dotnet build --configuration Release
    - name: Run Extractor
      run: |
        cd extractor
        cd src
        cd azure-api-management-devops-resource-kit-1.0.0-beta.3
        cd src
        cd ArmTemplates
        mkdir prTemplates
        dotnet run extract --sourceApimName ${{ github.event.inputs.instance-name }} --destinationApimName ${{ github.event.inputs.destination-name }} --resourceGroup ${{ github.event.inputs.resource-group-name }} --fileFolder ./prTemplates
    - name: Validate Template Files Structure
      run: ls -R
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
          **/prTemplates
        token: ${{ secrets.GH_TOKEN }}
        commit-message: New API pull from DEV
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: dev-patches
        delete-branch: true
        title: '[Automated] New API pull from DEV'
        body: |
          Pull API extract from DEV
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        reviewers: mitulashah
        team-reviewers: |
          owners
          maintainers
        draft: false