name: Generate Pull Request

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      instance-name:
        description: 'Name of source APIM instance'
        default: 'apim-'
        required: true
      destination-name:
        description: 'Name of destination APIM instance'
        default: 'apim-'
        required: true
      resource-group-name:
        description: 'Name of resource group'
        default: "rg-"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Download Extractor Release
      run: |
        mkdir extractor
        cd extractor
        gh release download 1.0.0-beta.3 --repo 'Azure/azure-api-management-devops-resource-kit' --archive=zip
        ls -R
        unzip -q azure-api-management-devops-resource-kit-1.0.0-beta.3 -d ./src
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build Extractor Release
      run: |
        cd src
        cd azure-api-management-devops-resource-kit-1.0.0-beta.3
        cd src 
        cd ArmTemplates
        dotnet build --configuration Release
    - name: Run Extractor
      run: |
        mkdir prTemplates
        dotnet run extract --sourceApimName ${{ github.event.inputs.instance-name }} --destinationApimName ${{ github.event.inputs.destination-name }} --resourceGroup ${{ github.event.inputs.resource-group-name }} --fileFolder ./prTemplates
    - name: Validate Template Files Structure
      run: ls -R
    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: '[Example] Simple demo',
            owner,
            repo,
            head: '${{ github.ref_name }}',
            base: 'develop',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });