name: APIM CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
  ARM_DEPLOY_MODE: validate

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo
        uses: actions/checkout@v3
      
      - name: Upload Templates
        uses: actions/upload-artifact@v3
        with: 
          name: templates
          path: .

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: prepare

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Templates
        uses: actions/download-artifact@v3
        with: 
          name: templates

      - name: Validate Template Files Structure
        run: ls -R

      - name: Deploy Products Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-products.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy Tags Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-tags.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy Named Values Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-namedValues.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy Backends Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-backends.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy APIs Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-apis.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json
      
      - name: Deploy Product / API Association Template
        uses: Azure/arm-deploy@v1.0.8
        if: ${{env.ARM_DEPLOY_MODE != 'validate'}}
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-productAPIs.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy API / Tags Association Template
        uses: Azure/arm-deploy@v1.0.8
        if: ${{env.ARM_DEPLOY_MODE != 'validate'}}
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-apiTags.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

      - name: Deploy Global Policy Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          resourceGroupName: rg-apimdemos-devops
          template: ./apimdevops-dev-globalServicePolicy.template.json
          deploymentMode: ${{env.ARM_DEPLOY_MODE}}
          parameters: ./apimdevops-dev-parameters.json

  deploy-qa:
    runs-on: ubuntu-latest
    environment: 'qa'
    needs: [prepare, deploy-dev]

    steps:
     - name: Echo
       run: echo Hello, world!